export enum LabelTypes {
    NONE = "NONE",
    POINT = "POINT",
    LINE = "LINE",
    RECTANGLE = "RECTANGLE",
    CIRCLE = "CIRCLE",
    POLYGON = "POLYGON",
    ARROW = "ARROW",
    CUBOID = "CUBOID",
    FREEHAND = "FREEHAND",
    PAINTBRUSH = "PAINTBRUSH",
    SEGMENTATION = "SEGMENTATION"

}